### ISSUE TITLE
Memory allocating issue

### ISSUE THREAD

**Issue by ozodrukh** [wangjiegulu/ShadowViewHelper#3]
Hi, great work, but you have [allocation issue](https://github.com/wangjiegulu/ShadowViewHelper/blob/master/library/src/main/java/com/wangjie/shadowviewhelper/ShadowViewDrawable.java#L72)

you should create a new Rect field, and set bounds after that draw reference to this variable

**Comment by wangjiegulu** [comment]
It's my mistake. I fixed it right now. Thank you so mach :-)
